### ISSUE TITLE
Replace socket-io client library

### ISSUE THREAD

**Issue by lucalas** [lucalas/StreamlabsArduinoAlerts#2]
Replace the use of socket-io client library with socket-io class inside of arduinowebsocket to avoid incompatibility problems.
Related to [#1](https://github.com/lucalas/StreamlabsArduinoAlerts/issues/1) opened issue.

**Comment by lambader** [comment]
Hi Lucas,
I tried everything but couldn't get it to work.
I may have corrupted the arduino program while I was tampering with it.
Does deleting and reinstalling save the program?
What should be the arduino library versions I should use.
I send you error pictures. My instagram mesut8989 .
