### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by JulianS-Uni** [lucalas/StreamlabsArduinoAlerts#3]
https://github.com/lucalas/StreamlabsArduinoAlerts/blob/c9e74984146c862b474fd884a290ecf40982ee32/library.properties#L10

Some is wring with your dependencies. Those are the dependencies that worked within PlatformIO for me:

	etidbury/SocketIoClient@^1.0.0
	bblanchon/ArduinoJson@^6.17.2

**Comment by lucalas** [comment]
Thanks, right now I want to remove SocketIoClient dependency (it's deprecated), this is the issue correlated [#2](https://github.com/lucalas/StreamlabsArduinoAlerts/issues/2) so the dependencies will change.
Let me know if there's something else or i'll close the issue.

**Comment by lucalas** [comment]
Thanks, right now I want to remove SocketIoClient dependency (it's deprecated), this is the issue correlated #2 so the dependencies will change.
Let me know if there's something else or i'll close the issue.
