### ISSUE TITLE
connection 

### ISSUE THREAD

**Issue by GlennVanLaere** [lucalas/StreamlabsArduinoAlerts#7]
hi, i am very new to arduino and i have this school project where i need to use this. 

So as i am trying to follow the readme i cant get to connect without errors

`#include <SocketIoClient.h>
#include <ArduinoJson.h>
#include <StreamlabsAPI.h>

char* socketToken = "token";
StreamlabsAPI streamlabsAPI.connect(socketToken);`

this is everything in my project and i get this error: 
`error: expected initializer before '.' token
    7 | StreamlabsAPI streamlabsAPI.connect(socketToken);
      |                            ^
exit status 1
expected initializer before '.' token`

I just don't understand how i can do something wrong...

**Comment by lucalas** [comment]
Hi @GlennVanLaere sorry for being inactive for so long.
The first thing that you have to do is to update the library to the new version released today [1.0.0](https://github.com/lucalas/StreamlabsArduinoAlerts/releases/tag/1.0.0) .

Try again a let me know.
If you still have problems, please share your code using tools like [pastebin](https://pastebin.com/) or share a repo with the code.

**Comment by lucalas** [comment]
No update received, I'm closing the issue.
If you still have problems feel free to open a new issue.
