### ISSUE TITLE
The problem continues.

### ISSUE THREAD

**Issue by lambader** [lucalas/StreamlabsArduinoAlerts#8]
Hi lucalas 
The problem continues. Can someone collect and upload old working files in a folder?
I need old arduino version and all old working library.
I've been trying for months and couldn't find a solution.

**Comment by lucalas** [comment]
hi @lambader sorry for being inactive for so long but here we have good news.
New release [1.0.0](https://github.com/lucalas/StreamlabsArduinoAlerts/releases/tag/1.0.0) is out!🎉🎉

It should solve your problems, I'm closing the issue, feel free to open a new one in case of any trouble.
